name: HelenTaranowski
favicon: null
layout_spectrum: 0.24764
typography_spectrum: 0.24494
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#414143'
    - '#fff301'
    - '#e2e0e1'
    - '#7d797a'
    - '#aeacad'
  brandStrength: 0.625
  lightness: 0.6767427544109523
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
